### PR TITLE
Upgrade to styled-components v3 and use secret internals

### LINKED ISSUE #112: Not working with styled-components v3.0.0
Broken as `styled-components` isn't shipping with `/lib` anymore (https://github.com/styled-components/styled-components/releases/tag/v3.0.1)

```
Cannot find module 'styled-components/lib/models/StyleSheet' from 'utils.js
```

### PR DESCRIPTION
**Pull request by philpl**
Fix #112

This uses the new secret internals that were added in styled-components@3.0.2, since the new v3 versions now use flat bundles and don't expose the `lib/` folder at all.

@MicheleBertoli There are some failing tests which I'm not sure about. Didn't know how to fix them but I think they might be related to an upgrade of stylis?

### CODE REVIEW

**Comment by philpl** [comment]
@MicheleBertoli Is that it? Will she live, doctor? :wink: Feel free to merge and release whenever you're ready. Can't wait :heart: thanks for your swift action 🙌

**Comment by MicheleBertoli** [comment]
It works with v3 (and v2 as well), and I'll remove the support for v1 soon.
Thank you very much, @philpl - you are awesome.
