### ISSUE TITLE
jest-styled-components is breaking with new 5.0.0 styled-components

### ISSUE THREAD

**Issue by santaclauze** [styled-components/jest-styled-components#297]
We just udpated to styled-components 5.0.0 and our snapshot tests are breaking:

```
    > 3 | import 'jest-styled-components';

Could neither find styled-components secret internals nor styled-components/lib/models/StyleSheet.js
```

I can see that you had the pre 5.0.0 your `package.json`.

Is this expected?

**Comment by ARXChrono** [comment]
That error you see has been resolved when you update jest-styled-components to 7.0.0

**Comment by ARXChrono** [comment]
However theres a few other errors occurring for me after upgrading, would be nice to see the changelog to 7.0.0

**Comment by pgsandstrom** [comment]
I have upgraded to 7.0.0 and are experiencing the exact samt problem.

**Comment by BatuhanW** [comment]
`toHaveStyleRule` expectations are failing after upgrading styled components to 5 and jest-styled-components to 7.

**Comment by SoontirFell** [comment]
@BatuhanW do the failing expects happen to contain modifiers with single quotes, i.e. is it the same issue as #296 ?

**Comment by moarwick** [comment]
yup, styled-components 5.0 + jest-styled-components 7.0 + Typescript also not happy:
```
error TS2339: Property 'toHaveStyleRule' does not exist on type 'JestMatchersShape<Matchers<void, HTMLElement>, Matchers<Promise<void>, HTMLElement>>'
```

**Comment by hutber** [comment]
Having the same issues, sadly

**Comment by BatuhanW** [comment]
> @BatuhanW do the failing expects happen to contain modifiers with single quotes, i.e. is it the same issue as #296 ?

I don't think. Because we have `singleQuote` set to false on prettierrc.

**Comment by hamatoyogi** [comment]
I'm also experiencing issues for tests that used to work on v4.4...
places where `toHaveStyleRule` is used are generating:
`Error: No style rules found on passed Component`

**Comment by Thomazella** [comment]
Can confirm this is broken. Does a version rollback fix?

**Comment by probablyup** [comment]
@Thomazella yes we dropped support for v4 with the v7 release. The internals changed a lot between v4 and v5 and the library needed incompatible updates.

**Comment by Duncan00** [comment]
Thanks. I tried `jest-styled-components v6` is working fine with `styled-components v4`.

**Comment by lucianomlima** [comment]
Not working with react-native v0.61.5 and `styled-components` v5 / `jest-styled-components` v7.
Get `TypeError: global.beforeEach is not a function`

**Comment by mirco312312** [comment]
@lucianomlima  are you using global installation approach? 

Note the deprecation warning here: https://jestjs.io/docs/en/configuration#setupfilesafterenv-array

When importing from a file referenced via `jest.setupFilesAfterEnv` its working for me with v5/v7.

**Comment by lucianomlima** [comment]
> @lucianomlima are you using global installation approach?
> 
> Note the deprecation warning here: https://jestjs.io/docs/en/configuration#setupfilesafterenv-array
> 
> When importing from a file referenced via `jest.setupFilesAfterEnv` its working for me with v5/v7.

No, i'm not using global installation and I use `jest.setupFilesAfterEnv` too. I'm try it again and maybe create a repro repo.

**Comment by lucianomlima** [comment]
@mirco312312 Thanks! I got working now!

**Comment by raurir** [comment]
thanks @mirco312312 - since it took me more than a few minutes to solve, here was the diff in my `package.json` that worked:

replaced: `"setupFiles": ["./spec/setupTests.js"],`
with: `"setupFilesAfterEnv": ["<rootDir>/spec/setupTests.js"],`

**Comment by webbhead777** [comment]
@raurir thanks! that solved the `TypeError: global.beforeEach is not a function` for me 👍

**Comment by Soul244** [comment]
after two months, the problem is still exists.

**Comment by PravallikaVinod** [comment]
import 'jest-styled-components';

Could neither find styled-components secret internals

styled-components - 4.4.1 and jest-styled-components - 7.0.2

Can anyone help me to solve this error

**Comment by wdonet** [comment]
I can confirm that for me it is working with this config:
- "styled-components": "^4.3.2"
- "jest-styled-components": "^6.3.4",

...🤔 @PravallikaVinod , try these versions or those combinations mentioned at comments above

**Comment by sebas-bytelion** [comment]
Its happend to me, when i use `import 'jest-styled-components/native';`, any update about it ?

**Comment by Soul244** [comment]
simple and ugly way:

add those two commands to your package.json scripts block. To start your test, run prepareTest command and downgrade libraries. When you revert library versions, run prepareStart. If you use npm or want to add specific version, change the scripts.

 "scripts": {
    "prepareStart": "yarn add styled-components --latest && yarn add -D jest-styled-components --latest",
    "prepareTest": "yarn add styled-components@4.4.1 && yarn add -D jest-styled-components@6.3.3",
  },

**Comment by kdalkafoukis** [comment]
Temporary? workaround for `"styled-components": "^5.1.0"` and `"jest-styled-components": "^7.0.2"` is to render the component inside the test.

- reference https://styled-components.com/docs/tooling#tohavestylerule
- same thing for enzyme
### failing test

```
import React from 'react';
import renderer from 'react-test-renderer'
import 'jest-styled-components';

import styled from 'styled-components'

const Button = styled.button`
  color: red;
`

describe('Button', () => {
    const app = renderer.create(<Button />).toJSON()
    it('Button has red color', () => {
        expect(app).toHaveStyleRule('color', 'red');
    });

});
```

![image](https://user-images.githubusercontent.com/4775609/82586885-f2df1400-9ba0-11ea-91ac-8dadf15f2675.png)


### workable test

```
import React from 'react';
import renderer from 'react-test-renderer'
import 'jest-styled-components';

import styled from 'styled-components'

const Button = styled.button`
  color: red;
`

describe('Button', () => {
    it('Button has red color', () => {
        const app = renderer.create(<Button />).toJSON()
        expect(app).toHaveStyleRule('color', 'red');
    });
});
```

![image](https://user-images.githubusercontent.com/4775609/82586946-08ecd480-9ba1-11ea-93a5-f25a7958f197.png)

**Comment by Tokimon** [comment]
I also have this problem as well using react-test-renderer and the latest versions:

```
"jest-styled-components": "^7.0.2",
"react-test-renderer": "16.13.1",
"styled-components": "^5.1.1",
```

I have tried the various suggested solutions above, but nothing have helped so far. Any news on any official solution?

**Comment by Tokimon** [comment]
So I had a look under the hood and the culprit is this regular expression here:

```js
const staticClassNames = classNames.filter(x => /^(\w+(-|_))?sc-/.test(x));
```

the problem is that it is looking for any class name this this sort of configuration:
`something-sc-xxx` or `something_sc-xxx` or `sc-xxx`

In my configuration none of my styled-components class names have this prefix I have for example a class name list like this:

```js
[ 'Tab__TabElement-gNeteQ', 'fjgULR', 'Tab', '', 'active' ]
```

The reason is that I have `ssr: false` in my `babel-plugin-styled-components` options.

So my solution (for now) is to set the `ssr: true` in my babel config, like so:

```js
[
  'babel-plugin-styled-components',
  { ssr: true }
]
```

However I think it is very unfortunate that I HAVE to have this option activated to not break my tests when upgrading to the latest version of `jest-styled-components` since this option is normally optional and as such you cannot guarantee that everybody have this option activated. Since this requirement is not described in the documentation I am not surprised that many people find that their tests break when upgrading.

So looking at the check that is being done to determine the the rules, it is directly reliant on having static class names, so if you don't use those the entire check fails:

```js
return classNames.some(className =>
    staticClassNames.some(staticClassName =>
      selectors.includes(
        getModifiedClassName(
          className,
          staticClassName,
          options.modifier
        ).replace(/['"]/g, '"')
      )
    )
  );
```

this has to be redone somehow to not be directly reliant on the static class names.
If you want I can try and look into doing a fix. Let me know.

**Comment by vxcamiloxv** [comment]
this was fixed on https://github.com/styled-components/jest-styled-components/pull/302 (v7.0.2) https://github.com/styled-components/jest-styled-components/pull/313 (master)

**Comment by noahnu** [comment]
#302 does not fix the issue. jest-styled-components looks for the presence of "sc-" anywhere in the component id. babel-plugin-styled-components does not guarantee that the component id will contain the "sc-" substring.

The issue is that babel-plugin-styled-components only applies the "sc-" prefix if it detects the component ID has an invalid css classname, [specifically whether it is prefixed by a digit](https://github.com/styled-components/babel-plugin-styled-components/blob/55b43ee70bdd8cd20ba942577e3747879cf1b44b/src/utils/prefixDigit.js#L2).

Temporarily fixed in my project via [patch-package](https://github.com/ds300/patch-package) and the following patch for version 1.10.7 which [modifies the getComponentId function](https://github.com/styled-components/babel-plugin-styled-components/blob/55b43ee70bdd8cd20ba942577e3747879cf1b44b/src/visitors/displayNameAndId.js#L133) to ensure it contains "sc-":

```diff
diff --git a/node_modules/babel-plugin-styled-components/lib/visitors/displayNameAndId.js b/node_modules/babel-plugin-styled-components/lib/visitors/displayNameAndId.js
index b67a1c8..2b41702 100644
--- a/node_modules/babel-plugin-styled-components/lib/visitors/displayNameAndId.js
+++ b/node_modules/babel-plugin-styled-components/lib/visitors/displayNameAndId.js
@@ -127,7 +127,8 @@ var getNextId = function getNextId(state) {
 
 var getComponentId = function getComponentId(state) {
   // Prefix the identifier with a character because CSS classes cannot start with a number
-  return `${(0, _prefixDigit.default)(getFileHash(state))}-${getNextId(state)}`;
+  var componentId = `${(0, _prefixDigit.default)(getFileHash(state))}-${getNextId(state)}`;
+  return componentId.indexOf('sc-') >= 0 ? componentId : `sc-${componentId}`;
 };
 
 var _default = function _default(t) {

```

**Comment by markwoodward23** [comment]
For us this was caused by having the babel-plugin-styled-components babel plugin running while running jest. Splitting out the babelrc file to have different envs for prod + test fixed the issue, though I've no idea why. 

See https://github.com/babel/babel-preset-env/issues/189#issuecomment-284466362 for a guide on using envs in babelrc.

**Comment by markwoodward23** [comment]
This does seem to stem from an issue in `babel-plugin-styled-components` for us - removing it does fix the issue. To achieve this while preserving prod behaviour we've split the .babelrc file into envs, not running `babel-plugin-styled-components` in test mode. 

See https://github.com/babel/babel-preset-env/issues/189#issuecomment-284466362 for a reference of how to split babelrc files into envs.

**Comment by Tokimon** [comment]
I concur with @noahnu that the problem resides in the fact that not all class names are being prefixed by `sc-` (I did not make the link with the digit in the class name so thank you for the clarification).

And I also agree that a correction has to be done in `babel-plugin-styled-component` since it is a bit inconsistent right now.

But the questions is if it is logical that for `jest-style-components` to find any class names any styled-component class name HAVE to contain `sc-`? I guess it makes it easier to determine styled-components class names, and as such improve performance, but it makes it less flexible. And (at least what I have seen) the documentation does not clearly state that `ssr` has to be activated for it to work.

**Comment by noahnu** [comment]
On that note, is it better to just remove the class name filtering entirely?

**Comment by stephen-boynton** [comment]
We are having the exact same problem. @noahnu 's fix does not fix the issue for use. We still receive the original error `Could neither find styled-components secret internals nor styled-components/lib/models/StyleSheet.js`. It is only during testing that this is an issue.

**Comment by vxcamiloxv** [comment]
well this require also a fix from babel plugin side https://github.com/styled-components/babel-plugin-styled-components/pull/276, you can use https://www.npmjs.com/package/@univision/babel-plugin-styled-components that have that fix

**Comment by stephen-boynton** [comment]
The fix I was referring to was a fix for the babel plugin.

**Comment by BonnieMilian** [comment]
for me worked with this versions:
`"styled-components": "^5.2.3"`
`"jest-styled-components": "^7.0.3"`

```
import '@testing-library/jest-dom/extend-expect'
import 'jest-styled-components'
import { screen } from '@testing-library/react'

// ...

expect(screen.getByTitle('some-title')).toHaveStyleRule('color', 'white')

```

**Comment by phaux** [comment]
I'm not using babel plugin, only jest with ts-jest preset. v4/v6 works. v5/v7 doesn't.
